spring:
  application:
    name: gateway-server

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

zuul:
  prefix: /api
  routes:
    stock-indice-service:
      path: /stock-indice-service/**
      url: http://localhost:8083
    currency-service:
      path: /currency-service/**
      url: http://localhost:8084
    client-ui:
      path: /client-ui/**
      url: http://localhost:8085