server:
  port: 8081
  enableSelfPreservation: true
  
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 3600
  client:
    registerWithEureka: false
    fetchRegistry: false